const todoActionTypes = {
    ADD_TODO: "ADD_TODO",
    REMOVE_TODO: "REMOVE_TODO",
    EDIT_TODO: "EDIT_TODO",
    MARK_TODO_COMPLETED: "MARK_TODO_COMPLETED",
    SORT_BY_NEWEST_FIRST: "SORT_BY_NEWEST_FIRST",
    SORT_BY_OLDEST_FIRST: "SORT_BY_OLDEST_FIRST"
}

export default todoActionTypes